# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UuSfNgGEUm8rLN1-HOpFXrA0EkxMTkP

#Q3

import random
import numpy as np
import matplotlib.pyplot as plt
x=[]
y=[]
for i in range(20):
a=random.randint(-40, 40) b=random.randint(-40, 40) x.append(a)
y.append(b)
file.close()
plt.scatter(x, y) plt.show()
"""

pip install nose

import random
import numpy as np
import matplotlib.pyplot as plt
from nose.tools import assert_equal

x=[]
y=[]
coordinates=[]
for i in range(20):
  a=random.randint(-40,40)
  b=random.randint(-40,40)
  x.append(a)
  y.append(b)
with open("clouds.txt",'w',encoding = 'utf-8',) as f:
  for i in range(0,len(x)):
    coordinates.append([x[i],y[i]])
    f.write(str(coordinates[i]))
    f.write(" \n")
  plt.scatter(x,y)
  plt.show()
  #f.write()
  # f.close()
with open("clouds.txt",'r',encoding = 'utf-8',) as f1:
  print(f1.read())

distance = []
for i in range(len(coordinates)):
  for j in range(len(coordinates)):
    if(i !=j):
      mindist= ((coordinates[i][0] - coordinates[j][0])*2 + (coordinates[i][1]-coordinates[j][1]))*0.5
      distance.append([coordinates[i],coordinates[j],mindist])
# for i in range(0,len(distance)):
#   # print(distance[i],"\n")
n= len(distance)
for i in range(n): 
  for j in range(n - 1 - i): 
    if distance[j][2] < distance[j + 1][2]: 
      distance[j], distance[j + 1] = distance[j + 1], distance[j]  
print(distance[n-1])